---
title: "player_gameplay"
author: "Tu hao wei"
Date: "2018/9/27"
output: html_document
---

## Test 1 (fail, name with blank)
```{r}
library(ggplot2)
mydata = read.csv("lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = mydata, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) 

```

## Test 2(take out blank, but "Name"s overlap)
```{r}
library(ggplot2)
mydata = read.csv("lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)  

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = getData, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) 

```

## Test 3(plot the picture by team)
```{r}
#uncompleted


library(ggplot2)
mydata = read.csv("lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)  

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = getData, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) 

```