---
title: "player_gameplay"
author: "Tu hao wei"
Date: "2018/9/27"
output: html_document
---

## Test 1 (fail, name with blank)
```{r}
library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = mydata, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) 

```

## Test 2(take out blank, but "Name"s overlap)
```{r}
library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)  

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = getData, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) 

```

## Test 3(plot the picture by team selected)
```{r}
library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)
mydata$Team = as.character(mydata$Team)

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#get the data of player in Cloud9
#https://stackoverflow.com/questions/5391124/select-rows-of-a-matrix-that-meet-a-condition
#how to extract rows that meet a condition (the website above)
team.name <- "Cloud9"
team.Data <- getData[getData[, "Team"] == team.name,]

#ggtitle("title_name") <- add title 
ggplot( data = team.Data, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) + ggtitle(team.name)

```


## Test 3.1(Rotate vertically x axis texts)
```{r}
library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)  

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#if you want to geom_bar with x,y -> stat = "identity"
ggplot( data = getData, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

## Test 4(plot the picture by team) Failed
```{r}
#uncompleted

library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)
mydata$Team = as.character(mydata$Team)

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#create a vector storing all team names
#https://stat.ethz.ch/R-manual/R-devel/library/base/html/append.html
#how to append value to vector (the website above)
all.team.name <- getData$Team[1]
i <- 2
repeat{
  if( is.na(getData$Team[i]) ) break
  if( !(getData$Team[i] %in% all.team.name) ) {
    all.team.name <- append(all.team.name, getData$Team[i], length(all.team.name))
  }
  i <- i + 1
}

#plot the data of player in team (one by one)
#http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/

#if(!require(devtools)) install.packages("devtools")
#devtools::install_github("kassambara/ggpubr")
#use above two lines to install package

#failed
library(ggpubr)
graph <- vector()
for(i in 1:length(all.team.name)){
  team.name <- all.team.name[i]
  team.Data <- getData[getData[, "Team"] == team.name,]
  graph[i] <- list(ggplot( data = team.Data, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) + ggtitle(team.name) + theme(axis.text.x = element_text(angle = 90, hjust = 1)))
}

```

## Test 5 (plot the picture by team) Failed, player names overlap again
```{r}
library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)
mydata$Team = as.character(mydata$Team)

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#create a vector storing all team names
#https://stat.ethz.ch/R-manual/R-devel/library/base/html/append.html
#how to append value to vector (the website above)
all.team.name <- getData$Team[1]
i <- 2
repeat{
  if( is.na(getData$Team[i]) ) break
  if( !(getData$Team[i] %in% all.team.name) ) {
    all.team.name <- append(all.team.name, getData$Team[i], length(all.team.name))
  }
  i <- i + 1
}

#plot the data of player in team (one by one)
#http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/

#if(!require(devtools)) install.packages("devtools")
#devtools::install_github("kassambara/ggpubr")
#use above two lines to install package

#failed
library(magrittr)
library(ggpubr)
graph <- ggplot(data = getData, aes(x = Name, y = Game.Played, fill = Team)) + geom_bar(stat = "identity") + facet_wrap(~Team)
graph

```


```{r}

library(ggplot2)
mydata = read.csv("../lcs-2017-summer-split-fantasy-player-team-stats/LCS Players Stats Summer Split 2017.csv")

#turn numeric into character
mydata$Name = as.character(mydata$Name)
mydata$Team = as.character(mydata$Team)

#find the data which is not blank and store into getData
getnnonameID = which(nchar(mydata$Name) != 0) 
getData = mydata[getnnonameID,]

#create a vector storing all team names
#https://stat.ethz.ch/R-manual/R-devel/library/base/html/append.html
#how to append value to vector (the website above)
all.team.name <- getData$Team[1]
i <- 2
repeat{
  if( is.na(getData$Team[i]) ) break
  if( !(getData$Team[i] %in% all.team.name) ) {
    all.team.name <- append(all.team.name, getData$Team[i], length(all.team.name))
  }
  i <- i + 1
}

#plot the data of player in team (one by one)
#http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/

#if(!require(devtools)) install.packages("devtools")
#devtools::install_github("kassambara/ggpubr")
#use above two lines to install package

#failed
library(ggpubr)
graph <- vector()
for(i in 1:length(all.team.name)){
  team.name <- all.team.name[i]
  team.Data <- getData[getData[, "Team"] == team.name,]
  print(ggplot( data = team.Data, aes(x = Name, y = Game.Played) ) + geom_bar( stat = "identity" ) + ggtitle(team.name) + coord_flip())
}
```

